# Generated by Django 4.1.5 on 2024-07-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("document_review", "0003_custom_user_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="custom_user",
            name="user_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="document_review.usertype",
            ),
            preserve_default=False,
        ),
    ]
