# Generated by Django 4.1.5 on 2024-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "document_review",
            "0006_file_filetype_reviewoperation_file_file_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewoperation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("confirm", "Confirm"),
                    ("request_modification", "Request Modification"),
                    ("reject", "Reject"),
                    ("pending", "Pending"),
                ],
                max_length=20,
            ),
        ),
    ]
