# Generated by Django 5.0.6 on 2024-07-16 12:28

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_review", "0008_custom_user_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custom_user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ASSISTANT", "Assistant"),
                    ("AUDITOR", "Auditor"),
                    ("SUPERVISOR", "Supervisor"),
                    ("MANAGER", "Manager"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
