# Generated by Django 5.0.6 on 2024-07-17 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_review", "0011_alter_reviewoperation_reviewed_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewoperation",
            name="uploaded_by",
        ),
        migrations.AlterField(
            model_name="reviewoperation",
            name="reviewed_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_operations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
