# Generated by Django 5.0.6 on 2024-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_review", "0013_alter_custom_user_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ["-upload_date"]},
        ),
        migrations.AlterModelOptions(
            name="reviewoperation",
            options={
                "ordering": [
                    models.Case(
                        models.When(operation_type="reject", then=0),
                        models.When(operation_type="request_modification", then=1),
                        models.When(operation_type="pending", then=2),
                        models.When(operation_type="confirm", then=3),
                        output_field=models.IntegerField(),
                    ),
                    "-operation_date",
                ]
            },
        ),
        migrations.AddField(
            model_name="file",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
