# Generated by Django 5.0.6 on 2024-07-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_review", "0017_filerequest_fileresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_files",
                to="document_review.custom_user",
            ),
        ),
        migrations.AlterField(
            model_name="filerequest",
            name="requested_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests_received",
                to="document_review.custom_user",
            ),
        ),
    ]
